input_dir: datasets
output_dir: emb_cache
models:
  - all-mpnet-base-v2
batch_size: 32
sources:
  human_data:
    - path: ivy_panda_essays.csv
  ai_data:
    - path: mistral_essays_1.csv
    - path: mistral_essays_2.csv
    - path: mistral_essays_3.csv
    - path: mistral_essays_4.csv
    - path: mistral_essays_5.csv
    - path: llama_essays_1.csv
    - path: llama_essays_2.csv
    - path: llama_essays_3.csv
    - path: llama_essays_4.csv
    - path: llama_essays_5.csv
    - path: deepseek_essays_1.csv
    - path: deepseek_essays_2.csv
    - path: deepseek_essays_3.csv
    - path: deepseek_essays_4.csv
    - path: deepseek_essays_5.csv
    - path: chatgpt_essays_1.csv
    - path: chatgpt_essays_2.csv
    - path: chatgpt_essays_3.csv
    - path: chatgpt_essays_4.csv
    - path: chatgpt_essays_5.csv