output_dir: train_results
models:
  - all-mpnet-base-v2
ae_epochs: 6
ae_batch_size: 8192
ae_lr: 1.0e-3
huggingface:
  upload: false
  repo_id: "artfultom/ae-ai-text-detector"
  token: null
  readme_template: "configs/model_readme_template.md"